### ISSUE TITLE
Selecting the fire pixel and having your brush off the grid causes a yellow overlay

### ISSUE THREAD

**Issue by SampleProvider** [definitely-nobody-is-here/red-pixel-simulator#5] opened 2023-09-17 16:06 UTC
![image](https://github.com/definitely-nobody-is-here/red-pixel-simulator/assets/68207888/20cd18a6-605c-43eb-9572-aa405b0d2b2f)

**Comment by SampleProvider** [comment] 2023-09-17 16:12
why is it invlaid

**Comment by spsquared** [comment] 2023-09-17 16:13
![image](https://github.com/definitely-nobody-is-here/red-pixel-simulator/assets/67865358/0a215108-10ac-41d5-befe-13f795c36063)
seems working to me

**Comment by spsquared** [comment] 2023-09-17 16:23
After looking through the code, fire is the only pixel that uses the old buffer canvas method of drawing noise. Everything else uses the grid overlay canvas, which is specifically for noise. (I'm going to rename it to grid noise canvas) Nothing else uses the buffer canvas, except the brush drawing code. Perhaps it has something to do with the game of life, but that pixel doesn't use the buffer, and nothing happened for me.

**Comment by spsquared** [comment] 2023-09-17 16:26
Ah, I had noise off. Now it happens. The fire pixel uses the buffer canvas in its rendering, but since the brush uses it too, having the brush off screen seems to make it also copy the buffer from the fire for some reason. Having it on-screen fixes it, and I'm not sure why that is. I'm not sure where it's clearing the canvas when you have the brush on grid. As long as anything is being drawn, it doesn't happen.

![image](https://github.com/definitely-nobody-is-here/red-pixel-simulator/assets/67865358/7d32f48e-52e5-497c-92d3-1b6af1da3494)

**Comment by spsquared** [comment] 2023-09-17 16:28
On a related note, any pixels that use the grid noise (grid overlay) canvas lose their noise in the brush since the overlay is not rendered, and fire, when not covering the screen with a yellow noise grid, is a yellow noise grid.

**Comment by spsquared** [comment] 2023-09-19 15:23
It is not caused by width/height of 0.
The fire draw uses the buffer canvas, which is also used for the brush drawing. For some reason, if the fire draws the buffer canvas onto the target canvas, it fixes the bug. However, adding an extra draw that sticks part of the buffer canvas on the target canvas doesn't fix it.
```
forRectangles(rectangles, (x, y, width, height, redrawing) => {
    ctx.drawImage(bufferCanvas, x * drawScale - camera.x, y * drawScale - camera.y, width * drawScale, height * drawScale, x * drawScale - camera.x, y * drawScale - camera.y, width * drawScale, height * drawScale);
});
```
I tried to change the pixels to not use the bufferCanvas and use noiseBufferCanvas instead (since it is meant for noise buffers and is used for other pixels). However, the other pixels also use the canvas, and the fire draw code fills the entire canvas with yellow, so it will either make everything yellow or remove all noise.

![image](https://github.com/definitely-nobody-is-here/red-pixel-simulator/assets/67865358/e7cc8a3c-e908-429b-a947-d51db56c73e0)

**Comment by spsquared** [comment] 2023-09-20 01:42
I don't want to add another canvas, and seeing that other pixels (except water and lava) lose their noise in the brush, I'll just make it not draw noise in the brush, since even when it works it doesn't really work.

**Comment by spsquared** [comment] 2023-09-20 01:43
The main cause is when the target canvas is the buffer canvas, meaning the draw code actually draws the canvas on itself. It should be fixed now, even though the fire loses its noise. I'll just say it's less distracting or something.

**Comment by spsquared** [comment] 2023-09-20 01:45
Forgot to reference this issue in commit, oops.

**Closed as completed by spsquared** 2023-09-20 01:45 UTC
Labels: bug

**Comment by spsquared** [comment] 2023-09-20 16:38
Technically, the root bug isn't fixed. I'll probably open a new issue about noise not working in the brush.

Also, I can't update fire to use the new noise method since it will override the noise of pixels below it and does not remove the noise when the fire is removed, resulting in yellow ghosting.

![image](https://github.com/definitely-nobody-is-here/red-pixel-simulator/assets/67865358/acf7fcac-251b-4fb0-bec2-d810ed695de4)

**Comment by SampleProvider** [comment] 2023-09-20 23:52
you cant just fix the bug by removing the feature
